os: osx
dist: trusty
language: generic

sudo: false

before_install:
 - brew update

matrix:
  include:
    - env: version=HEAD_python3
      install:
      - brew upgrade python
      - pip3 install numpy
      - travis_wait 50 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3 --without-numpy
    - env: version=current_python3
      install:
      - brew upgrade python
      - pip3 install numpy
      - travis_wait 50 brew install ./Formula/rdkit.rb --build-from-source --with-python3 --without-numpy
    - env: version=HEAD_python2
      install: travis_wait 50 brew install ./Formula/rdkit.rb --HEAD --build-from-source --without-numpy
    - env: version=current_python2
      install: travis_wait 50 brew install ./Formula/rdkit.rb --build-from-source --without-numpy
