os: osx
language: generic

sudo: true

before_install:
 - brew update
 - brew upgrade python
 # Don't need `pip2 install numpy` because numpy has already been install: see https://docs.travis-ci.com/user/reference/osx/#Python-related-tools
 - if [ "$NUMPY_VERSION" == "PIP" ]; then pip3 install numpy; fi
 - if [ "$NUMPY_VERSION" == "HOMEBREW" ]; then sudo easy_install pip; fi
 - if [ "$NUMPY_VERSION" == "HOMEBREW" ]; then sudo pip2 uninstall numpy; fi

matrix:
  include:
    - env:
        - version=HEAD_python3
        - NUMPY_VERSION=PIP
      install: travis_wait 50 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3 --without-numpy
    - env:
        - version=current_python3
        - NUMPY_VERSION=PIP
      install: travis_wait 50 brew install ./Formula/rdkit.rb --build-from-source --with-python3 --without-numpy
    - env:
        - version=HEAD_python2
        - NUMPY_VERSION=PIP
      install: travis_wait 50 brew install ./Formula/rdkit.rb --HEAD --build-from-source --without-numpy
    - env:
        - version=current_python2
        - NUMPY_VERSION=PIP
      install: travis_wait 50 brew install ./Formula/rdkit.rb --build-from-source --without-numpy
    - env:
        - version=HEAD_python3
        - NUMPY_VERSION=HOMEBREW
      install: travis_wait 50 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3
    - env:
        - version=current_python3
        - NUMPY_VERSION=HOMEBREW
      install: travis_wait 50 brew install ./Formula/rdkit.rb --build-from-source --with-python3
