os: osx
dist: trusty
language: generic

sudo: false

matrix:
  include:
    - before_install:
        - brew update
        - brew install python3
        - pip2 install numpy
        - pip3 install numpy
      install: travis_wait 50 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3 --without-numpy
      env: version=HEAD options=without_numpy
    - before_install:
        - brew update
        - brew install python3
        - pip2 install numpy
        - pip3 install numpy
      install: travis_wait 50 brew install ./Formula/rdkit.rb --build-from-source --with-python3 --without-numpy
      env: version=current options=without_numpy
    - before_install:
        - brew update
      install: travis_wait 50 brew install ./Formula/rdkit.rb --build-from-source
      env: version=current options=with_numpy
