os: osx
dist: trusty

sudo: false

before_install:
 - brew update
 - brew install python3
 - pip3 install numpy

install:
 - brew install --build-from-source ./Formula/rdkit.rb --with-python3 --without-numpy