os: osx
dist: trusty
language: generic

sudo: false

before_install:
 - brew upgrade python
 - brew install python3
 - pip3 install numpy

matrix:
  include:
    - install:
        - travis_wait 30 brew install ./Formula/boost@1.66.rb
        - travis_wait 20 brew install ./Formula/boost-python3@1.66.rb --build-from-source
        - travis_wait 20 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3 --without-numpy
      env:
        - version=HEAD
    - install:
        - travis_wait 30 brew install ./Formula/boost@1.66.rb --build-from-source
        - travis_wait 20 brew install ./Formula/boost-python3@1.66.rb --build-from-source
        - travis_wait 20 brew install ./Formula/rdkit.rb --build-from-source --with-python3 --without-numpy
      env:
        - version=current
      